/*
 * Common Plugin for all modules
 */
plugins {
    id 'groovy'
}

repositories {
    mavenCentral()
    mavenLocal()
    maven {
        url = 'https://m2.dv8tion.net/releases'
    }
    maven {
        name "lavalinkDevReleases"
        url "https://maven.lavalink.dev/releases"
    }
}

test {
    useJUnitPlatform()
    testLogging {
        events "passed", "skipped", "failed"
    }
}
