[versions]
spring = '6.2.9'
google-guava = '33.4.8-jre'
jakarta-annotations = '3.0.0'

discordJda = '5.6.1'
# Snapshot version for most recent youtube API fix
# lavaplayer = 'afec211f05c9dcf0b6ee44276a02f0316ea2458a-SNAPSHOT'
lavaplayer = '2.2.6'
lavaplayer-youtube = '1.18.0'

mongodb = '5.5.1'

jackson = '2.19.2'
joptSimple = '5.0.4'

slf4j = '2.0.17'
log4j = '2.25.1'
jansi = '2.4.2'

# Test
spock = '2.4-M6-groovy-4.0'
hamcrest = '2.2'
byteBuddy = '1.10.10'
objenesis = '3.1'

[libraries]
# Spring
spring-bom = { module = 'org.springframework:spring-bom', version.ref = 'spring' }
spring-core = { module = 'org.springframework:spring-core', version.ref = 'spring' }
spring-context = { module = 'org.springframework:spring-context', version.ref = 'spring' }
spring-beans = { module = 'org.springframework:spring-beans', version.ref = 'spring' }

# Util
google-guava = { module = 'com.google.guava:guava', version.ref = 'google-guava' }
jakarta-annotations = { module = 'jakarta.annotation:jakarta.annotation-api', version.ref = 'jakarta-annotations' }

# Discord JDS API
discordJda = { module = 'net.dv8tion:JDA', version.ref = 'discordJda' }

# Lavaplayer for music streaming
lavaplayer = { module = 'dev.arbjerg:lavaplayer', version.ref = 'lavaplayer' }
# lavalink youtube-source v2 rewritten source manager for lavaplayer
lavaplayer-youtube = { module = 'dev.lavalink.youtube:v2', version.ref = 'lavaplayer-youtube' }

# Mongo
mongodb-bom = { module = 'org.mongodb:mongodb-driver-bom', version.ref = 'mongodb' }

# JSON
jackson-bom = { module = 'com.fasterxml.jackson.core:jackson-bom', version.ref = 'jackson' }
jackson-core = { module = 'com.fasterxml.jackson.core:jackson-core', version.ref = 'jackson' }
jackson-databind = { module = 'com.fasterxml.jackson.core:jackson-databind', version.ref = 'jackson' }
jackson-annotations = { module = 'com.fasterxml.jackson.core:jackson-annotations', version.ref = 'jackson' }
jackson-datatype-jdk8 = { module = 'com.fasterxml.jackson.datatype:jackson-datatype-jdk8', version.ref = 'jackson' }
jackson-dataformat-properties = { module = 'com.fasterxml.jackson.dataformat:jackson-dataformat-properties', version.ref = 'jackson' }

joptSimple = { module = 'net.sf.jopt-simple:jopt-simple', version.ref = 'joptSimple' }

# Logging
slf4j-api = { module = 'org.slf4j:slf4j-api', version.ref = 'slf4j' }
slf4j-ext = { module = 'org.slf4j:slf4j-ext', version.ref = 'slf4j' }

log4j-api = { module = 'org.apache.logging.log4j:log4j-api', version.ref = 'log4j' }
log4j-core = { module = 'org.apache.logging.log4j:log4j-core', version.ref = 'log4j' }
log4j-slf4j = { module = 'org.apache.logging.log4j:log4j-slf4j2-impl', version.ref = 'log4j' }
jansi = { module = 'org.fusesource.jansi:jansi', version.ref = 'jansi' }

# === Testing
# mandatory dependencies for using Spock
spock-bom = { module = 'org.spockframework:spock-bom', version.ref = 'spock' }
spock-core = { module = 'org.spockframework:spock-core', version.ref = 'spock' }

# Optional dependencies for using Spock
hamcrest = { module = 'org.hamcrest:hamcrest-core', version.ref = 'hamcrest' }
byteBuddy = { module = 'net.bytebuddy:byte-buddy', version.ref = 'byteBuddy' }
objenesis = { module = 'org.objenesis:objenesis', version.ref = 'objenesis' }


[bundles]

core = [
    'spring-core',
    'spring-beans',
    'spring-context',
    'google-guava',
    'slf4j-api',
    'slf4j-ext',
    'jakarta-annotations'
]

jackson = [
    'jackson-core',
    'jackson-annotations',
    'jackson-databind',
    'jackson-datatype-jdk8',
    'jackson-dataformat-properties'
]

log4j = [
    'log4j-api',
    'log4j-core',
    'log4j-slf4j',
    'jansi'
]

spock = [
    'spock-core',
    'hamcrest',
    'byteBuddy',
    'objenesis',
]


[plugins]

