plugins {
    id 'java-library'
    id 'com.tavern.groovy-common-conventions'

    id("org.openrewrite.rewrite") version "7.11.0"
}

dependencies {
    implementation platform(project(':platform'))
    implementation project(':domain')
    implementation project(':utilities')

    implementation libs.bundles.core
    implementation libs.lavaplayer
    implementation libs.lavaplayer.youtube
    implementation libs.discordJda

    // Your current JDA version before upgrading to 6.0.0
    implementation("net.dv8tion:JDA:5.+")

    rewrite("net.dv8tion:JDA:6.0.0")
    rewrite("org.openrewrite.recipe:rewrite-java-dependencies:1.37.0")
}

rewrite {
    activeRecipe("net.dv8tion.MigrateComponentsV2")
}
