
plugins {
    id 'java'
    id 'application'
    id 'distribution'
    id 'com.tavern.groovy-common-conventions'
}

def appName = 'tavern'
def mainClassName = 'com.tavern.app.App'
version = '1.0.0'
description = 'Tavern discord integration'

dependencies {
    implementation platform(project(':platform'))
    implementation project(':utilities')
    implementation project(':discord')
    implementation project(':domain')
    implementation project(':audio')
    implementation project(':repository')

    implementation libs.bundles.core
    implementation libs.bundles.jackson
    implementation libs.joptSimple

    runtimeOnly libs.bundles.log4j
}

application {
    // Define the main class for the application.
    mainClass = mainClassName

    // Enable log4j2 colored logging
    applicationDefaultJvmArgs = [ '-Dlog4j.skipJansi=false', "-Dtavern.version=$version" ]
}

tasks.named("run") {
    // Change working dir to root project dir instead of app project dir
    workingDir = file(rootDir)
}

distributions {
    main {
        distributionBaseName = 'tavern'

        contents {
            from('../', {
                include 'tavern-discord.properties'
            })

            include 'tavern*'
        }
    }
}

jar {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
    manifest {
        attributes 'Main-Class': application.mainClass
    }
    archiveBaseName = 'tavern'

    dependsOn configurations.runtimeClasspath
    from {
        configurations.runtimeClasspath.findAll { it.name.endsWith('jar') }.collect { zipTree(it) }
    }
}

tasks.named('startScripts', CreateStartScripts) {
    applicationName = appName
}
